/*  Copyright (C) 2011-2012 National Institute For Space Research (INPE) - Brazil.

This file is part of the TerraLib - a Framework for building GIS enabled applications.

TerraLib is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License,
or (at your option) any later version.

TerraLib is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with TerraLib. See COPYING. If not, write to
TerraLib Team at <terralib-team@terralib.org>.
*/

/*!
\file fiocruz/src/fiocruz/flow/FlowGraphImport.cpp

\brief This file defines the Flow Graph Import class
*/


#include "FlowGraphImport.h"

//terralib
#include <terralib/datatype/SimpleData.h>
#include <terralib/datatype/SimpleProperty.h>
#include <terralib/geometry/GeometryProperty.h>
#include <terralib/geometry/MultiLineString.h>
#include <terralib/graph/Globals.h>
#include <terralib/graph/core/AbstractGraph.h>
#include <terralib/graph/core/AbstractGraphFactory.h>
#include <terralib/graph/core/GraphMetadata.h>
#include <terralib/graph/core/Edge.h>
#include <terralib/graph/core/Vertex.h>


te::qt::plugins::fiocruz::FlowGraphImport::FlowGraphImport()
{
  m_edgeId = 0;
}

te::qt::plugins::fiocruz::FlowGraphImport::~FlowGraphImport()
{

}

te::graph::AbstractGraph* te::qt::plugins::fiocruz::FlowGraphImport::importGraph(std::auto_ptr<te::da::DataSet> dataSet, int originIdx, int destinyIdx, int weightIdx, int geomidx)
{
  te::graph::AbstractGraph* graph = buildGraph();

  //fill graph
  dataSet->moveBeforeFirst();

  while (dataSet->moveNext())
  {
    std::string originId = dataSet->getAsString(originIdx);
    std::string destinyId = dataSet->getAsString(destinyIdx);
    std::string weightStr = dataSet->getAsString(weightIdx);

    //get geometry from edge (lineString with 2 coords)
    std::auto_ptr<te::gm::Geometry> geom = dataSet->getGeometry(geomidx);
    te::gm::LineString* line = getLine(geom.get());

    if (line)
    {
      //check if graph has the origin vertex
      te::graph::Vertex* vFrom = graph->getVertex(atoi(originId.c_str()));

      if (!vFrom)
      {
        //create vertex
        vFrom = new te::graph::Vertex(atoi(originId.c_str()));
        vFrom->setAttributeVecSize(1); //geom only

        //create geom point
        te::dt::AbstractData* ad = new te::gm::Point(*line->getPointN(0));
        vFrom->addAttribute(0, ad);

        //add to graph
        graph->add(vFrom);
      }

      //check if graph has the destiny vertex
      te::graph::Vertex* vTo = graph->getVertex(atoi(destinyId.c_str()));

      if (!vTo)
      {
        //create vertex
        vTo = new te::graph::Vertex(atoi(destinyId.c_str()));
        vTo->setAttributeVecSize(1); //geom only

        //create geom point
        te::dt::AbstractData* ad = new te::gm::Point(*line->getPointN(1));
        vTo->addAttribute(0, ad);

        //add to graph
        graph->add(vTo);
      }

      //create edge
      if (vFrom && vTo)
      {
        int id = getEdgeId();

        te::graph::Edge* e = new te::graph::Edge(id, vFrom->getId(), vTo->getId());

        e->setAttributeVecSize(3); //from, to, weight

        e->addAttribute(0, new te::dt::SimpleData<int, te::dt::INT32_TYPE>(vFrom->getId()));
        e->addAttribute(1, new te::dt::SimpleData<int, te::dt::INT32_TYPE>(vTo->getId()));
        e->addAttribute(2, new te::dt::SimpleData<int, te::dt::INT32_TYPE>(atoi(weightStr.c_str())));

        graph->add(e);
      }
    }
  }

  return graph;
}

te::graph::AbstractGraph* te::qt::plugins::fiocruz::FlowGraphImport::buildGraph()
{
  std::string graphName = "flowGraph";

  // data source information
  std::map<std::string, std::string> connInfo;

  // graph type
  std::string graphType = te::graph::Globals::sm_factoryGraphTypeBidirectionalGraph;

  // graph information
  std::map<std::string, std::string> graphInfo;
  graphInfo["GRAPH_DATA_SOURCE_TYPE"] = "MEM";
  graphInfo["GRAPH_NAME"] = graphName;
  graphInfo["GRAPH_DESCRIPTION"] = "Generated by Flow Builder.";

  te::graph::AbstractGraph* graph =  te::graph::AbstractGraphFactory::make(graphType, connInfo, graphInfo);

  //create vertex attributes
  te::gm::GeometryProperty* gProp = new te::gm::GeometryProperty("coords");
  gProp->setId(0);
  gProp->setGeometryType(te::gm::PointType);

  graph->addVertexProperty(gProp);

  //create edge attributes
  {//add from property to graph
    te::dt::SimpleProperty* p = new te::dt::SimpleProperty("from", te::dt::INT32_TYPE);
    p->setParent(0);
    p->setId(0);
    graph->addEdgeProperty(p);
  }

  {//add to property to graph
    te::dt::SimpleProperty* p = new te::dt::SimpleProperty("to", te::dt::INT32_TYPE);
    p->setParent(0);
    p->setId(0);
    graph->addEdgeProperty(p);
  }

  {//add weight property to graph
    te::dt::SimpleProperty* p = new te::dt::SimpleProperty("weight", te::dt::INT32_TYPE);
    p->setParent(0);
    p->setId(0);
    graph->addEdgeProperty(p);
  }

  return graph;
}

te::gm::LineString* te::qt::plugins::fiocruz::FlowGraphImport::getLine(te::gm::Geometry* geom)
{
  assert(geom);

  te::gm::LineString* line = 0;

  if (geom->getGeomTypeId() == te::gm::LineStringType)
  {
    line = dynamic_cast<te::gm::LineString*>(geom);
  }
  else if (geom->getGeomTypeId() == te::gm::MultiLineStringType)
  {
    te::gm::MultiLineString* multiLine = dynamic_cast<te::gm::MultiLineString*>(geom);
    
    if (multiLine)
      line = dynamic_cast<te::gm::LineString*>(multiLine->getGeometryN(0));
  }

  return line;
}

int  te::qt::plugins::fiocruz::FlowGraphImport::getEdgeId()
{
  int id = m_edgeId;

  m_edgeId++;

  return id;
}

